name: Keep GitHub Pages Alive

on:
  schedule:
    - cron: '*/15 * * * *' # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keepAlive:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🕒 Update timestamp
        run: |
          echo "Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" > timestamp.txt

      - name: 🔐 Configure Git and Commit
        run: |
          git config user.name "Dani"
          git config user.email "danitadesse367@gmail.com"
          git add timestamp.txt
          git commit -m "Keep alive: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
