name: Keep GitHub Pages Alive

on:
  schedule:
    - cron: '0 0 */10 * *'
  workflow_dispatch:

jobs:
  keepAlive:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update timestamp
        run: |
          echo "Last updated: $(date)" > timestamp.txt
          git config user.name "Dani"
          git config user.email "danitadesse367@gmail.com"
          git add timestamp.txt
          git commit -m "Keep alive: $(date)"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
